import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { supabaseServer } from "../lib/supabase/server";
import Header from "../components/Header";
import Footer from "../components/Footer";
import InitUser from "../lib/store/initUser";
import { Toaster } from "sonner";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "E-commerce",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const supabase = await supabaseServer();
  const { data } = await supabase.auth.getSession();
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header />
        {children}
        <Toaster position="top-center" />
        <Footer />
        <InitUser user={data?.session?.user} />
      </body>
    </html>
  );
}
